### ISSUE TITLE
Can't build on UE4.27

### ISSUE THREAD

**Issue by jonathanatn** [heroiclabs/nakama-unreal#122]
Again, still cannot build the plugin with Unreal 4.27...

> Error	C2665	'FParse::Value': none of the 14 overloads could convert all the argument types	Atlassia	C:\Users\User\Desktop\UEShipping\Plugins\Nakama\Source\NakamaTests\Public\NakamaTestBase.h	54	
> Error	C2039	'IsEmpty': is not a member of 'TArray<FNakamaFriend,FDefaultAllocator>'	Atlassia	C:\Users\User\Desktop\UEShipping\Plugins\Nakama\Source\NakamaTests\Private\Tests\Test_Friends.cpp	37	
> Error	C2039	'IsEmpty': is not a member of 'TArray<FNakamaFriend,FDefaultAllocator>'	Atlassia	C:\Users\User\Desktop\UEShipping\Plugins\Nakama\Source\NakamaTests\Private\Tests\Test_Friends.cpp	48	
> Error	C2039	'IsEmpty': is not a member of 'TMap<FString,FString,FDefaultSetAllocator,TDefaultMapHashableKeyFuncs<KeyType,ValueType,false>>'	Atlassia	C:\Users\User\Desktop\UEShipping\Plugins\Nakama\Source\NakamaTests\Private\Tests\Test_RestoreSession.cpp	19	
> Error	C2039	'__this': is not a member of 'TArray<FNakamaFriend,FDefaultAllocator>'	Atlassia	C:\Users\User\Desktop\UEShipping\Plugins\Nakama\Source\NakamaTests\Private\Tests\Test_Friends.cpp	37	
> Error	C2039	'__this': is not a member of 'TArray<FNakamaFriend,FDefaultAllocator>'	Atlassia	C:\Users\User\Desktop\UEShipping\Plugins\Nakama\Source\NakamaTests\Private\Tests\Test_Friends.cpp	48

**Comment by jonathanatn** [comment]
I commented out since it's only errors from test file
