### ISSUE TITLE
nakama-unreal 2.8.1 can't build with UE5.1.1

### ISSUE THREAD

**Issue by rollaroll** [heroiclabs/nakama-unreal#99]
When I use UE5.1.1 to generate visual studio project files, an error occurred, but it seems to work in the 5.3 preview
Is the latest version of the plugin no longer planned to support engine versions below 5.2 ?

Here are logs:
Running C:/Program Files/Epic Games/UE_5.1/Engine/Build/BatchFiles/Build.bat  -projectfiles -project="C:/Game/test/nakama-unreal-2.8.1/NakamaTest/NakamaTest.uproject" -game -rocket -progress -log="C:\Game\test\nakama-unreal-2.8.1\NakamaTest/Saved/Logs/UnrealVersionSelector-2023.08.04-19.18.18.log"
Running UnrealBuildTool: dotnet "..\..\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" -projectfiles -project="C:/Game/test/nakama-unreal-2.8.1/NakamaTest/NakamaTest.uproject" -game -rocket -progress -log="C:\Game\test\nakama-unreal-2.8.1\NakamaTest/Saved/Logs/UnrealVersionSelector-2023.08.04-19.18.18.log"
Log file: C:\Game\test\nakama-unreal-2.8.1\NakamaTest\Saved\Logs\UnrealVersionSelector-2023.08.04-19.18.18.log
Log file: C:\Users\nyapas\AppData\Local\UnrealBuildTool\Log_GPF.txt

Some Platforms were skipped due to invalid SDK setup: IOS, Android, Linux, LinuxArm64.
See the log file for detailed information

Discovering modules, targets and source code for project...
C:\Game\test\nakama-unreal-2.8.1\NakamaTest\Source\NakamaTest\NakamaTest.Build.cs(18,40): error CS0103: The name 'UnrealArch' does not exist in the current context
C:\Game\test\nakama-unreal-2.8.1\NakamaTest\Plugins\Nakama\Source\NakamaCore\NakamaCore.build.cs(22,40): error CS0103: The name 'UnrealArch' does not exist in the current context
C:\Game\test\nakama-unreal-2.8.1\NakamaTest\Plugins\Nakama\Source\NakamaCore\NakamaCore.build.cs(26,45): error CS0103: The name 'UnrealArch' does not exist in the current context
Expecting to find a type to be declared in a target rules named 'NakamaTestTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.

**Comment by AdLegg85** [comment]
Hey, its not going to help your issue but im currently having the same problem!! i also opened a ticket about it! when i add the plugin and enable it the engine will restart and when it tries to compule the plugin it fails! getting errors about UnrealArch when i try and build the solution.

I am also on 5.1.1 but tested this on latest UE4 and got the same issues?? so this will work on 5.3?

**Comment by lugehorsam** [comment]
Hi @rollaroll this will be fixed in a release next week.

**Comment by lugehorsam** [comment]
This should be fixed in the latest release.

**Comment by mikef-wildlight** [comment]
> This should be fixed in the latest release.

I'm not sure if this is specific to us, but in our UE5.1 x64 Windows project Target.Architecture is an empty string.

**Comment by lugehorsam** [comment]
Hey @mikef-wildlight, we'll incorporate the following into a patch release if it works when you modify `NakamaCore.Build.cs`.

```
#if UE_5_2_OR_LATER
		return Target.Architecture == UnrealArch.X64;
#else
		// empty string is the "default architecture" which is x64
		return Target.Architecture == "" || Target.Architecture.StartsWith("x86_64") || Target.Architecture.StartsWith("x64");
#endif
```

**Comment by lugehorsam** [comment]
@mikef-wildlight great, this will be resolved in v2.9.0 which should come out in the next couple of days.
